- id: "/"
  title: "ICPS2017"
  description: "ICPS 2017 - International Conference of Physics Students: Torino, Italy, 7-14 August 2017."
  keywords: "icps 2017 torino physics students aisf iaps"
- id: "/speakers/"
  title: "ICPS 2017 | Speakers"
  description: "ICPS 2017 - Speakers of the Conference."
  keywords: "icps 2017 speakers physics"