- id: "/"
  title: "ICPS 2017"
  description: "ICPS 2017 - International Conference of Physics Students: Torino, Italy, 7-14 August 2017. Organized by AISF and IAPS for Bachelor, Master, and PhD Physics students."
  keywords: "icps 2017 torino physics students aisf iaps"
- id: "/speakers"
  title: "ICPS 2017 | Speakers"
  description: "We are committed to host a number of world-leading scientists and researchers in multiple areas of physics."
  keywords: "icps 2017 speakers physics"
- id: "/registration"
  title: "ICPS 2017 | Registration"
  description: "Register here for the International Conference of Physics Students 2017. The registration process includes and Early Round in February-March and a Late Round in March-April."
- id: "/documents"
  title: "ICPS 2017 | Documents"
  description: "Flyers, Prospects and Posters regarding ICPS, AISF and IAPS."
- id: "/excursions"
  title: "ICPS 2017 | Excursions"
  description: "On Friday we offer a wide range of excursions, including both a scientific and cultural component."
- id: "/scientific-contributions"
  title: "ICPS 2017 | Scientific Contributions"
  description: "Participants are encouraged to present the result of their works with either a poster or a talk."
- id: "/voluneteers-call"
  title: "ICPS 2017 | Volunteers Call"
  description: "A strong team of volunteers is required to cover every organizational aspect of the event."